routes/web.php
<?php

use App\Http\Controllers\accountController;
use App\Http\Controllers\ItemsController;
use App\Http\Controllers\MealsController;
use App\Http\Controllers\MenusController;
use App\Http\Controllers\showallController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/account', function () {
    return view('account');
})->name('account');

Auth::routes();
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::resource('item',ItemsController::class)->middleware('auth');
Route::resource('meal',MealsController::class)->middleware('auth');
Route::resource('menu',MenusController::class)->middleware('auth');
Route::get('/', [App\Http\Controllers\Controller::class, 'index'])->name('home');
Route::get('/account/modification', [accountController::class,'index'])->name('modif');
Route::post('/account/modification', [accountController::class,'changepass'])->name('changepass');
Route::delete('meal/delete/{meal}', [MealsController::class, 'delete'])->name('meal.delete');
Route::get('/showall/items', [showallController::class,'showitem'])->name('showitems');
Route::get('/showall/meals', [showallController::class,'showmeals'])->name('showmeals');
Route::get('/showall/menus/', [showallController::class,'showmenu'])->name('showmenu');
Route::get('/showall/{slug}', [showallController::class,'showmenu']);
Route::get('/showall/menus/{id}', [showallController::class,'showm'])->name('showm');
Route::get('/showall/meals/{id}', [showallController::class,'showme'])->name('showme');
Route::get('/showall/items/{id}', [showallController::class,'showit'])->name('showit');
Route::post('/showall/recherche', [showallController::class,'recherche'])->name('recherche');
Route::delete('item/force/{id}', [ItemsController::class, 'forceDestroy'])->name('item.force.destroy');
Route::put('item/restore/{id}', [ItemsController::class, 'restore'])->name('item.restore');
Route::delete('meal/force/{id}', [MealsController::class, 'forceDestroy'])->name('meal.force.destroy');
Route::put('meal/restore/{id}', [MealsController::class, 'restore'])->name('meal.restore');
Route::delete('menu/force/{id}', [MenusController::class, 'forceDestroy'])->name('menu.force.destroy');
Route::put('menu/restore/{id}', [MenusController::class, 'restore'])->name('menu.restore');

app/Models/Meals.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Meals extends Model
{
    use HasFactory,SoftDeletes;
    protected $fillable = ['title', 'image', 'description','price','user_id'];

    public function Item()
    {
        return $this->belongsToMany(Item::class);
    }
    public function user()
    {

        return $this->belongsTo(User::class);


    }
}

app/Http/Controllers/MealsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Item;
use App\Models\Meals;
use App\Models\Menu;
use Illuminate\Http\Request;

class MealsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $meals= Meals::withTrashed()->oldest('title')->paginate(5);
        return view('Meals/index', compact('meals'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $menuss = Item::all();

        return view('/Meals/create',compact('menuss'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        $meal = new Meals();
        $meal->title = $input['title'];
        $meal->description = $input['description'];
        $meal->price = $input['price'];
        $input["user_id"] = \Auth::user()->id;
        $meal->user_id =   $input["user_id"];
        if (isset($input['image'])){
            $meal->image =  $this->upload($input['image']) ;
        }
        $meal->save();
        $meal->item()->attach($input['itemsmenu']);
        return redirect()->route('item.index')->with('info', 'Le item a bien été créer ');
    }

    public function upload ($file){
        $extension = $file->getClientOriginalExtension();
        $sha1 = sha1($file->getClientOriginalName());
        $filename = date('Y-m-d-h-i-s').$sha1.".".$extension ;
        $path = public_path('images/');
        $file->move($path,$filename);
        return 'images/'.$filename ;

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

          $meals=Meals::where('id',$id)->first();
        return view('Meals/show',compact('meals'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $meals=Meals::where('id',$id)->first();
        $allItem= Item::all();
        return view('Meals/edit', compact('meals','allItem'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();
        $meal = Meals::where('id',$id)->first();
        $im = $meal->image;
        $meal->title = $input['title'];
        $meal->description = $input['description'];
        $input["user_id"] = \Auth::user()->id;
        $meal->user_id =   $input["user_id"];
        if (isset($input['image'])){
            $meal->image =  $this->upload($input['image']) ;

        }
        else { $meal->image =$im;}

        $meal->update();
        $meal->item()->sync($input['itemsmenu']);
        return redirect()->route('meal.index')->with('info', 'Le Meal a bien été
modifié');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delete($id)
    {

       Meals::findOrfail($id)->delete();
        return back()->with('info', 'Le film a bien été mis dans la corbeille.');
    }

    public function restore($id)
    {
        Meals::withTrashed()->whereId($id)->firstOrFail()->restore();
        return back()->with('info', 'Le film a bien été restauré.');
    }

    public function forceDestroy($id)
    {
        Meals::withTrashed()->whereId($id)->firstOrFail()->forceDelete();
        return back()->with('info', 'Le film a bien été supprimé définitivement dans
la base de données.');
    }
}

app/Http/Controllers/api/MealController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Meals;
use Illuminate\Http\Request;

class MealController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return Meals::all();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Meals::create($request->all());
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $meals= Meals::where('id',$id)->first();
        return $meals;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $meals= Meals::where('id',$id)->first();
        $meals->update($request->all());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       $meals= Meals::where('id',$id)->first();
        $meals->delete();
    }
}

resources/views/Meals/create.blade.php
@extends('welcome')

@section('content')
    <h1>Create Menu</h1>

    <form  method="post" action="{{ route('meal.store') }}" enctype="multipart/form-data">
        @csrf
        <div id="items">
            <div class="form-group"><label for="items_title" class="required">Title</label><input type="text" id="title" name="title" required="required" maxlength="255" class="form-control" value=""></div>
            <div class="form-group"><label for="items_description" class="required">Description</label><input type="text" id="items_description" name="description" required="required" maxlength="255" class="form-control" value=""></div>
            <div class="form-group">
                <label for="items_image">Image</label>
                <div class="custom-file"><input type="file" id="items_image" name="image" lang="en" class="custom-file-input"><label for="items_image" class="custom-file-label"></label>
                </div>
            </div>
            <div class="form-group"><label for="items_price" class="required">Price</label><input type="text" id="items_price" name="price" required="required" class="form-control" value=""></div>
            <div class="form-group">
                <label class="" for="items_menu">Menu</label>

                <select id="items_menu" name="itemsmenu[]" class="form-control" multiple>
                    @foreach( $menuss as $menusss)

                        <option {{ in_array($menusss->id, old('itemsmenu') ?: []) ? 'selected' : '' }}  value="{{ $menusss->id }}"  >{{ $menusss->title }}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <button class="btn btn-outline-primary" style="    margin: -21px;
      margin-top: 34px;">Update</button>
    </form>

    <a href="{{ route('menu.index') }}" Class="btn btn-outline-secondary" style="    margin-top: -21px;
    margin-left: 115px;">back to list</a>

    {{--{{ include('items/_delete_form.html.twig') }}--}}
@endsection

resources/views/Meals/edit.blade.php
@extends('welcome')

@section('content')
<h1>Edit Menus </h1>

<form  method="post" action="{{ route('meal.update',$meals->id) }}" enctype="multipart/form-data">
    @csrf
    @method('put')
    <div id="items">
        <div class="form-group"><label for="items_title" class="required">Title</label><input type="text" id="title" name="title" required="required" maxlength="255" class="form-control" value="{{ $meals->title }}"></div>
        <div class="form-group"><label for="items_description" class="required">Description</label><input type="text" id="items_description" name="description" required="required" maxlength="255" class="form-control" value="{{ $meals->description }}"></div>
        <div class="form-group">
            <label for="items_image">Image</label>
            <div class="custom-file"><input type="file" id="items_image" name="image" lang="en" class="custom-file-input"><label for="items_image" class="custom-file-label"></label>
            </div>
        </div>

        <div class="form-group">
            <label class="" for="items_menu">Menu</label>

            <select id="items_menu" name="itemsmenu[]" class="form-control" multiple>

                    @foreach ($allItem as $items )
                <option  value="{{ $items->id }}" >
                    {{$items->title}}
                    @endforeach
                </option>

            </select>
        </div>
    </div>
    <button class="btn btn-outline-primary" style="    margin: -21px;
      margin-top: 34px;">Update</button>
</form>

<a href="{{ route('meal.index') }}" Class="btn btn-outline-secondary" style="    margin-top: -21px;
    margin-left: 115px;">back to list</a>

{{--{{ include('items/_delete_form.html.twig') }}--}}
@endsection

resources/views/Meals/index.blade.php
@extends('welcome')

@section('content')
    <h1 style="font-family:'Dancing Script', cursive  !important;font-size: 67px;
    text-align: center; "class=" animate__animated animate__backInLeft">Meals Liste</h1>

    <a href="{{ route('meal.create') }}" class="btn btn-outline-dark" style="float: right;margin-bottom: 22px;">Create new</a>
    <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
        <tr>
            <th>Title</th>

            <th>Description</th>
            <th>Image</th>
            <th>Price</th>
            <th>CreatedBy</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($meals as $meal)
            <tr>


                <td>{{ $meal->title }}</td>
                <td>{{ $meal->description  }}</td>
                <td><img src="/images/{{ $meal->image }}" height="100px"></td>
                <td>{{ ($meal->price /100) |number_format(2)}}£</td>
                <td>{{ $meal->user->name}}</td>

                {{--                                <td>{{ menu.createdAt ? menu.createdAt|date('Y-m-d H:i:s') : '' }}</td>--}}
                {{--                                <td>{{ menu.updateAt ? menu.updateAt|date('Y-m-d H:i:s') : '' }}</td>--}}
                <td>
                    <a href="{{ route('meal.show',$meal->id) }}" class="btn btn-outline-primary" style="width: 80px">show</a>
                    <a href="{{ route('meal.edit',$meal->id) }}" class="btn btn-outline-warning" style="width:80px;">edit</a>
                    @if($meal->deleted_at)
                        <form action="{{ route('meal.restore', $meal->id) }}"

                              method="post">

                            @csrf
                            @method('PUT')
                            <button style="margin-left: 170px;margin-top: -67px;" class="btn btn-outline-success"

                                    type="submit">Restaurer</button>
                        </form>


                        <form action="{{
route('meal.force.destroy', $meal->id) }}"
                              method="post">
                            @csrf
                            @method('DELETE')

                            <button
                                class="btn btn-outline-danger" style="width:200px;margin-top: -114px;margin-left: 267px"
                                type="submit">Supprimer definitivement</button>
                        </form>
                    @else


                        <form action="{{
route('meal.delete', $meal->id) }}"
                              method="post">
                            @csrf
                            @method('DELETE')

                            <button
                                class="btn btn-outline-danger" style="width:100px;margin-top: -67px;margin-left:170px"
                                type="submit">Supprimer</button>
                        </form>
                @endif
            </tr>

        @endforeach

        </tbody>

    </table>
    <div class="navigation">
        {{ $meals->links() }}
    </div>


@endsection

resources/views/Meals/show.blade.php
@extends('welcome')

@section('content')
<div class="row">
    <div class="col-md-5">

        <img src="/images/{{ $meals->image }}" alt="{{ $meals->title }}" class="img-fluid">
    </div>
    <div class="col-md-7 my-auto">
        <h3>{{ $meals->title }}</h3>
        <p>{{ $meals->title }}</p>
        <span class="product-page-price">{{ ($meals->price / 100)|number_format(2) }} €</span>
        <hr>
        <p>
            {{ $meals->description }}
        </p>
    </div>
</div>
<hr>
<div style="text-align: center">
    @auth()
    <a href="{{ route('meal.index') }}"class="btn btn-outline-primary" style="">back to list</a>
    @endauth

</div>
       <h3>Meal Items</h3>
        <div class="row">

            @foreach($meals->item as $items)
                    <div class="col-md-3">
                        <div class="product-item text-center">
                            <a href=""><img src="/images/{{ $items->image }}" alt="{{ $items->title }}" class="img-fluid" style="border-radius: 130px;height: 253px;"></a>
                            <h5>{{ $items->title }}</h5>
                            <span class="product-subtitle">{{ $items->price }}</span>
                            <span class="product-subtitle">{{ $items->title }}</span>

                        </div>
                       </div>
            @endforeach
        </div><!-- /.row -->




@endsection