routes/web.php
<?php

use App\Http\Controllers\accountController;
use App\Http\Controllers\ItemsController;
use App\Http\Controllers\MealsController;
use App\Http\Controllers\MenusController;
use App\Http\Controllers\showallController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/account', function () {
    return view('account');
})->name('account');

Auth::routes();
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::resource('item',ItemsController::class)->middleware('auth');
Route::resource('meal',MealsController::class)->middleware('auth');
Route::resource('menu',MenusController::class)->middleware('auth');
Route::get('/', [App\Http\Controllers\Controller::class, 'index'])->name('home');
Route::get('/account/modification', [accountController::class,'index'])->name('modif');
Route::post('/account/modification', [accountController::class,'changepass'])->name('changepass');
Route::delete('meal/delete/{meal}', [MealsController::class, 'delete'])->name('meal.delete');
Route::get('/showall/items', [showallController::class,'showitem'])->name('showitems');
Route::get('/showall/meals', [showallController::class,'showmeals'])->name('showmeals');
Route::get('/showall/menus/', [showallController::class,'showmenu'])->name('showmenu');
Route::get('/showall/{slug}', [showallController::class,'showmenu']);
Route::get('/showall/menus/{id}', [showallController::class,'showm'])->name('showm');
Route::get('/showall/meals/{id}', [showallController::class,'showme'])->name('showme');
Route::get('/showall/items/{id}', [showallController::class,'showit'])->name('showit');
Route::post('/showall/recherche', [showallController::class,'recherche'])->name('recherche');
Route::delete('item/force/{id}', [ItemsController::class, 'forceDestroy'])->name('item.force.destroy');
Route::put('item/restore/{id}', [ItemsController::class, 'restore'])->name('item.restore');
Route::delete('meal/force/{id}', [MealsController::class, 'forceDestroy'])->name('meal.force.destroy');
Route::put('meal/restore/{id}', [MealsController::class, 'restore'])->name('meal.restore');
Route::delete('menu/force/{id}', [MenusController::class, 'forceDestroy'])->name('menu.force.destroy');
Route::put('menu/restore/{id}', [MenusController::class, 'restore'])->name('menu.restore');

app/Models/Menu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Menu extends Model
{
    protected $fillable = ['title', 'image', 'description','type','user_id'];

    use HasFactory,SoftDeletes;

    public function Item()
    {
        return $this->hasMany(Item::class);
    }
    public function user()
    {

        return $this->belongsTo(User::class);


    }

}

app/Http/Controllers/MenusController.php
<?php

namespace App\Http\Controllers;

use App\Models\Item;
use App\Models\Meals;
use App\Models\Menu;
use Illuminate\Http\Request;

class MenusController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $Menus= Menu::withTrashed()->oldest('title')->paginate(5);
        return view('Menus/index', compact('Menus'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('/Menus/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        $menu = new Menu();
        $menu->title = $input['title'];
        $menu->description = $input['description'];
        $input["user_id"] = \Auth::user()->id;
        $menu->user_id =   $input["user_id"];
        $menu->type = $input['itemsmenu'];
        if (isset($input['image'])){
            $menu->image =  $this->upload($input['image']) ;
        }
        if (isset($input['isbest'])){
            $menu->isbest =$input['isbest'];
        }
        $menu->save();
        return redirect()->route('menu.index')->with('info', 'Le menu a bien été créer ');
    }

    public function upload ($file){
        $extension = $file->getClientOriginalExtension();
        $sha1 = sha1($file->getClientOriginalName());
        $filename = date('Y-m-d-h-i-s').$sha1.".".$extension ;
        $path = public_path('images/');
        $file->move($path,$filename);
        return 'images/'.$filename ;

    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Menu $menu)
    {
        return view('Menus/show',compact('menu'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Menu $menu)
    {
        return view('Menus/edit', compact('menu'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();
        $menu = Menu::where('id',$id)->first();
        $im = $menu->image;
        $input["user_id"] = \Auth::user()->id;
        $menu->user_id =   $input["user_id"];
        $menu->title = $input['title'];
        $menu->description = $input['description'];
        $menu->type = $input['itemsmenu'];
        if (isset($input['image'])){
            $menu->image =  $this->upload($input['image']) ;

        }
        else { $menu->image =$im;}
        if (isset($input['isbest'])){
            $menu->isbest =$input['isbest'];
        }
        $menu->update();

        return back()->with('info', 'Le item a bien été modifié ');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Menu::findOrfail($id)->delete();
        return back()->with('info', 'Le film a bien été mis dans la corbeille.');
    }

    public function restore($id)
    {
        Menu::withTrashed()->whereId($id)->firstOrFail()->restore();
        return back()->with('info', 'Le film a bien été restauré.');
    }

    public function forceDestroy($id)
    {
        Menu::withTrashed()->whereId($id)->firstOrFail()->forceDelete();
        return back()->with('info', 'Le film a bien été supprimé définitivement dans
la base de données.');
    }
}

app/Http/Controllers/api/MenuController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Menu;
use Illuminate\Http\Request;

class MenuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         return Menu::all();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Menu::create($request->all());
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Menu $menu)
    {
        return $menu;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Menu $menu)
    {
        $menu->update($request->all());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy( Menu $menu)
    {
        $menu->delete();
    }
}

resources/views/Menus/create.blade.php
@extends('welcome')

@section('content')
    <h1>Create Menu</h1>

    <form  method="post" action="{{ route('menu.store') }}" enctype="multipart/form-data">
        @csrf
        <div id="items">
            <div class="form-group"><label for="items_title" class="required">Title</label><input type="text" id="title" name="title" required="required" maxlength="255" class="form-control" value=""></div>
            <div class="form-group"><label for="items_description" class="required">Description</label><input type="text" id="items_description" name="description" required="required" maxlength="255" class="form-control" value=""></div>
            <div class="form-group">
                <label for="items_image">Image</label>
                <div class="custom-file"><input type="file" id="items_image" name="image" lang="en" class="custom-file-input"><label for="items_image" class="custom-file-label"></label>
                </div>
            </div>
            <div class="form-group">
                <label class="" for="Tys">Type</label>

                <select id="items_menu" name="itemsmenu" class="form-control">

                        <option  value="food"  >food</option>
                        <option  value="Hot Drink"  >Hot Drink</option>
                        <option  value="Cold Drink"  >Cold Drink </option>

                </select>
            </div>
        </div>
        <button class="btn btn-outline-primary" style="    margin: -21px;
      margin-top: 34px;">Update</button>
    </form>

    <a href="{{ route('menu.index') }}" Class="btn btn-outline-secondary" style="    margin-top: -21px;
    margin-left: 115px;">back to list</a>

    {{--{{ include('items/_delete_form.html.twig') }}--}}
@endsection

resources/views/Menus/edit.blade.php
@extends('welcome')

@section('content')
<h1>Edit Menus </h1>

<form  method="post" action="{{ route('menu.update',$menu->id) }}" enctype="multipart/form-data">
    @csrf
    @method('put')
    <div id="items">
        <div class="form-group"><label for="items_title" class="required">Title</label><input type="text" id="title" name="title" required="required" maxlength="255" class="form-control" value="{{ $menu->title }}"></div>
        <div class="form-group"><label for="items_description" class="required">Description</label><input type="text" id="items_description" name="description" required="required" maxlength="255" class="form-control" value="{{ $menu->description }}"></div>
        <div class="form-group">
            <label for="items_image">Image</label>
            <div class="custom-file"><input type="file" id="items_image" name="image" lang="en" class="custom-file-input"><label for="items_image" class="custom-file-label"></label>
            </div>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" value="1" name="isbest" @if ($menu->isbest == 1)checked @endif>
            <label class="form-check-label" for="defaultCheck1">
                IsBest
            </label>
        </div>
        <div class="form-group">
            <label class="" for="items_menu">Menu</label>

            <select id="items_menu" name="itemsmenu" class="form-control">
                <option @if($menu->type == "food") selected @endif value="food"  >food</option>
                <option @if($menu->type == "Hot Drink") selected @endif value="Hot Drink"  >Hot Drink</option>
                <option @if($menu->type == "Cold Drink") selected @endif  value="Cold Drink"  >Cold Drink </option>
            </select>
        </div>
    </div>
    <button class="btn btn-outline-primary" style="    margin: -21px;
      margin-top: 34px;">Update</button>
</form>

<a href="{{ route('menu.index') }}" Class="btn btn-outline-secondary" style="    margin-top: -21px;
    margin-left: 115px;">back to list</a>

{{--{{ include('items/_delete_form.html.twig') }}--}}
@endsection

resources/views/Menus/index.blade.php
@extends('welcome')

@section('content')
    <h1 style="font-family:'Dancing Script', cursive  !important;font-size: 67px;
    text-align: center; "class=" animate__animated animate__backInLeft">Menus Liste</h1>

    <a href="{{ route('menu.create') }}" class="btn btn-outline-dark" style="float: right;margin-bottom: 22px;">Create new</a>
    <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
        <tr>
            <th>Title</th>

            <th>Description</th>
            <th>Image</th>
            <th>Price</th>
            <th>CreatedBy</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($Menus as $Menu)
            <tr>


                <td>{{ $Menu->title }}</td>
                <td>{{ $Menu->description  }}</td>
                <td><img src="/images/{{ $Menu->image }}" height="100px"></td>
                <td>{{ ($Menu->price /100) |number_format(2)}}£</td>
                <td>   {{ $Menu->user->name}}</td>

                {{--                                <td>{{ menu.createdAt ? menu.createdAt|date('Y-m-d H:i:s') : '' }}</td>--}}
                {{--                                <td>{{ menu.updateAt ? menu.updateAt|date('Y-m-d H:i:s') : '' }}</td>--}}
                <td>
                    <a href="{{ route('menu.show',$Menu->id ) }}" class="btn btn-outline-primary" style="width: 80px">show</a>
                    <a href="{{ route('menu.edit',$Menu->id ) }}" class="btn btn-outline-warning" style="width:80px;">edit</a>
                    @if($Menu->deleted_at)
                        <form action="{{ route('menu.restore', $Menu->id) }}"

                              method="post">

                            @csrf
                            @method('PUT')
                            <button style="margin-left: 170px;margin-top: -67px;" class="btn btn-outline-success"

                                    type="submit">Restaurer</button>
                        </form>


                        <form action="{{
route('menu.force.destroy', $Menu->id) }}"
                              method="post">
                            @csrf
                            @method('DELETE')

                            <button
                                class="btn btn-outline-danger" style="width:200px;margin-top: -114px;margin-left: 267px"
                                type="submit">Supprimer definitivement</button>
                        </form>
                    @else


                        <form action="{{
route('menu.destroy', $Menu->id) }}"
                              method="post">
                            @csrf
                            @method('DELETE')

                            <button
                                class="btn btn-outline-danger" style="width:100px;margin-top: -67px;margin-left:170px"
                                type="submit">Supprimer</button>
                        </form>
                @endif
            </tr>

        @endforeach

        </tbody>

    </table>
    <div class="navigation">
        {{ $Menus->links() }}
    </div>


@endsection

resources/views/Menus/show.blade.php
@extends('welcome')

@section('content')
<div class="row">
    <div class="col-md-5">
        <img src="/images/{{ $menu->image }}" alt="{{ $menu->title }}" class="img-fluid">
    </div>
    <div class="col-md-7 my-auto">
        <h3>{{ $menu->title }}</h3>
        <p>{{ $menu->title }}</p>
        <span class="product-page-price">{{ ($menu->price / 100)|number_format(2) }} €</span>
        <hr>
        <p>
            {{ $menu->description }}
        </p>
    </div>
</div>
<hr>
<div style="text-align: center">
    @auth()
    <a href="{{ route('menu.index') }}"class="btn btn-outline-primary" style="">back to list</a>

    <a href="{{ route('menu.edit', $menu->id) }}" class="btn btn-outline-warning" style="">edit</a>
    @endauth
{{--    {{ include('items/_delete_form.html.twig') }}--}}
</div>
       <h3>Nos meilleures ventes</h3>
        <p>Découvrez les articles les plus vendus.</p>
<div class="row">

    @foreach($menu->item as $items)
        <div class="col-md-3">
            <div class="product-item text-center">
                <a href=""><img src="/images/{{ $items->image }}" alt="{{ $items->title }}" class="img-fluid" style="border-radius: 130px;height: 253px;"></a>
                <h5>{{ $items->title }}</h5>
                <span class="product-subtitle">{{ $items->price }}</span>
                <span class="product-subtitle">{{ $items->title }}</span>

            </div>
        </div>
    @endforeach
</div><!-- /.row -->




@endsection