routes/web.php
<?php

use App\Http\Controllers\accountController;
use App\Http\Controllers\ItemsController;
use App\Http\Controllers\MealsController;
use App\Http\Controllers\MenusController;
use App\Http\Controllers\showallController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/account', function () {
    return view('account');
})->name('account');

Auth::routes();
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::resource('item',ItemsController::class)->middleware('auth');
Route::resource('meal',MealsController::class)->middleware('auth');
Route::resource('menu',MenusController::class)->middleware('auth');
Route::get('/', [App\Http\Controllers\Controller::class, 'index'])->name('home');
Route::get('/account/modification', [accountController::class,'index'])->name('modif');
Route::post('/account/modification', [accountController::class,'changepass'])->name('changepass');
Route::delete('meal/delete/{meal}', [MealsController::class, 'delete'])->name('meal.delete');
Route::get('/showall/items', [showallController::class,'showitem'])->name('showitems');
Route::get('/showall/meals', [showallController::class,'showmeals'])->name('showmeals');
Route::get('/showall/menus/', [showallController::class,'showmenu'])->name('showmenu');
Route::get('/showall/{slug}', [showallController::class,'showmenu']);
Route::get('/showall/menus/{id}', [showallController::class,'showm'])->name('showm');
Route::get('/showall/meals/{id}', [showallController::class,'showme'])->name('showme');
Route::get('/showall/items/{id}', [showallController::class,'showit'])->name('showit');
Route::post('/showall/recherche', [showallController::class,'recherche'])->name('recherche');
Route::delete('item/force/{id}', [ItemsController::class, 'forceDestroy'])->name('item.force.destroy');
Route::put('item/restore/{id}', [ItemsController::class, 'restore'])->name('item.restore');
Route::delete('meal/force/{id}', [MealsController::class, 'forceDestroy'])->name('meal.force.destroy');
Route::put('meal/restore/{id}', [MealsController::class, 'restore'])->name('meal.restore');
Route::delete('menu/force/{id}', [MenusController::class, 'forceDestroy'])->name('menu.force.destroy');
Route::put('menu/restore/{id}', [MenusController::class, 'restore'])->name('menu.restore');

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Item extends Model
{
    use HasFactory,SoftDeletes;

    Protected $fillable =['title','description','price','image','menu_id','user_id'] ;

    public function menu(){

        return $this->belongsTo(Menu::class);


    }

    public function Meal()
    {
        return $this->belongsToMany(Meals::class);
    }

    public function user()
    {

        return $this->belongsTo(User::class);


    }


    }

app/Http/Controllers/ItemsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Item;
use App\Models\Menu;
use Illuminate\Http\Request;

class ItemsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items= Item::withTrashed()->oldest('title')->paginate(5);
        return view('Items/index', compact('items'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $menuss = Menu::all();
        return view('/Items/create',compact('menuss'));


    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        $item = new Item();
        $item->title = $input['title'];
        $item->description = $input['description'];
        $item->price = $input['price'];
        $input["user_id"] = \Auth::user()->id;
        $item->user_id =   $input["user_id"];
        $item->menu_id = $input['itemsmenu'];
        if (isset($input['image'])) {
            $item->image = $this->upload($input['image']);

        }
         if (isset($input['isbest'])){
             $item->isbest =$input['isbest'];
    }
        $item->save();
        return redirect()->route('item.index')->with('info', 'Le item a bien été créer ');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Item $item)
    {

     return view('Items/show',compact('item'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Item $item)
    {
        $menu = $item->menu->title;
        $menuss = Menu::all();
        return view('Items/edit', compact('item','menu','menuss'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();
        $item = Item::where('id',$id)->first();
        $im = $item->image;
        $item->title = $input['title'];
        $item->description = $input['description'];
        $item->price = $input['price'];
        $input["user_id"] = \Auth::user()->id;
        $item->user_id =   $input["user_id"];
        if (isset($input['isbest'])){
            $item->isbest =$input['isbest'];
        }
        if (isset($input['image'])){
            $item->image =  $this->upload($input['image']) ;

        }
        else { $item->image =$im;}

        $item->update();

        return back()->with('info', 'Le item a bien été modifié ');

    }


    public function upload ($file){
        $extension = $file->getClientOriginalExtension();
        $sha1 = sha1($file->getClientOriginalName());
        $filename = date('Y-m-d-h-i-s').$sha1.".".$extension ;
        $path = public_path('images/');
        $file->move($path,$filename);
        return $filename ;

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Item::findOrfail($id)->delete();
        return back()->with('info', 'Le film a bien été mis dans la corbeille.');
    }

    public function restore($id)
    {
        Item::withTrashed()->whereId($id)->firstOrFail()->restore();
        return back()->with('info', 'Le film a bien été restauré.');
    }

    public function forceDestroy($id)
    {
        Item::withTrashed()->whereId($id)->firstOrFail()->forceDelete();
        return back()->with('info', 'Le film a bien été supprimé définitivement dans
la base de données.');
    }


}

app/Http/Controllers/api/ItemController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Item;
use Illuminate\Http\Request;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return Item::all();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Item::create($request->all());
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Item $item)
    {
        return $item;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Item $item)
    {
        $item->update($request->all());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Item $item)
    {
        $item->delete();
    }
}

resources/views/Items/create.blade.php
@extends('welcome')

@section('content')
    <h1>Create Items</h1>

    <form  method="post" action="{{ route('item.store') }}" enctype="multipart/form-data">
        @csrf
        <div id="items">
            <div class="form-group"><label for="items_title" class="required">Title</label><input type="text" id="title" name="title" required="required" maxlength="255" class="form-control" value=""></div>
            <div class="form-group"><label for="items_description" class="required">Description</label><input type="text" id="items_description" name="description" required="required" maxlength="255" class="form-control" value=""></div>
            <div class="form-group">
                <label for="items_image">Image</label>
                <div class="custom-file"><input type="file" id="items_image" name="image" lang="en" class="custom-file-input"><label for="items_image" class="custom-file-label"></label>
                </div>
            </div>
            <div class="form-group"><label for="items_price" class="required">Price</label><input type="text" id="items_price" name="price" required="required" class="form-control" value=""></div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="1" name="isbest">
                <label class="form-check-label" for="defaultCheck1">
                   IsBest
                </label>
            </div>
            <div class="form-group">


                <label class="" for="items_menu">Menu</label>

                <select id="items_menu" name="itemsmenu" class="form-control">
                    @foreach( $menuss as $menusss)

                        <option  value="{{ $menusss->id }}"  >{{ $menusss->title }}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <button class="btn btn-outline-primary" style="    margin: -21px;
      margin-top: 34px;">Update</button>
    </form>

    <a href="{{ route('item.index') }}" Class="btn btn-outline-secondary" style="    margin-top: -21px;
    margin-left: 115px;">back to list</a>

    {{--{{ include('items/_delete_form.html.twig') }}--}}
@endsection

resources/views/Items/edit.blade.php
@extends('welcome')

@section('content')
<h1>Edit Items</h1>

<form  method="post" action="{{ route('item.update',$item->id) }}" enctype="multipart/form-data">
    @csrf
    @method('put')
    <div id="items">
        <div class="form-group"><label for="items_title" class="required">Title</label><input type="text" id="title" name="title" required="required" maxlength="255" class="form-control" value="{{ $item->title }}"></div>
        <div class="form-group"><label for="items_description" class="required">Description</label><input type="text" id="items_description" name="description" required="required" maxlength="255" class="form-control" value="{{ $item->description }}"></div>
        <div class="form-group">
            <label for="items_image">Image</label>
            <div class="custom-file"><input type="file" id="items_image" name="image" lang="en" class="custom-file-input"><label for="items_image" class="custom-file-label"></label>
            </div>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" value="1" name="isbest" @if ($item->isbest == 1)checked @endif>
            <label class="form-check-label" for="defaultCheck1">
                IsBest
            </label>
        </div>
        <div class="form-group"><label for="items_price" class="required">Price</label><input type="text" id="items_price" name="price" required="required" class="form-control" value="{{ $item->price }}"></div>
        <div class="form-group">
            <label class="" for="items_menu">Menu</label>

            <select id="items_menu" name="itemsmenu" class="form-control">
                @foreach( $menuss as $menusss)

                    <option  @if ( $menu == $menusss->title ) selected @endif  value="{{ $menusss->id }}"  >{{ $menusss->title }}</option>
                @endforeach
            </select>
        </div>
    </div>
    <button class="btn btn-outline-primary" style="    margin: -21px;
      margin-top: 34px;">Update</button>
</form>

<a href="{{ route('item.index') }}" Class="btn btn-outline-secondary" style="    margin-top: -21px;
    margin-left: 115px;">back to list</a>

{{--{{ include('items/_delete_form.html.twig') }}--}}
@endsection

resources/views/Items/index.blade.php
@extends('welcome')

@section('content')
    @if(session()->has('info'))
        <div class="notification is-success">
            {{ session('info') }}
        </div>
        @endif
<h1 style="font-family:'Dancing Script', cursive  !important;font-size: 67px;
    text-align: center; "class=" animate__animated animate__backInLeft">Items Liste</h1>

<a href="{{ route('item.create') }}" class="btn btn-outline-dark" style="float: right;margin-bottom: 22px;">Create new</a>
<table id="example" class="table table-striped table-bordered" style="width:100%">
    <thead>
    <tr>
        <th>Title</th>

        <th>Description</th>
        <th>Image</th>
        <th>Price</th>
        <th>CreatedBy</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    @foreach($items as $item)
    <tr>


        <td>{{ $item->title }}</td>
        <td>{{ $item->description  }}</td>
        <td><img src="/images/{{ $item->image }}" height="100px"></td>
        <td>{{ ($item->price) |number_format(2)}}</td>
        <td>{{ $item->User->name }}</td>
        <td>
            <a href="{{ route('item.show',$item->id ) }}" class="btn btn-outline-primary" style="width: 80px">Show</a>
            <a href="{{ route('item.edit',$item->id) }}" class="btn btn-outline-warning" style="width:80px;">Edit</a>

            @if($item->deleted_at)
                <form action="{{ route('item.restore', $item->id) }}"

                      method="post">

                    @csrf
                    @method('PUT')
                    <button style="margin-left: 170px;margin-top: -67px;" class="btn btn-outline-success"

                            type="submit">Restaurer</button>
                </form>


                <form action="{{
route('item.force.destroy', $item->id) }}"
                      method="post">
                    @csrf
                    @method('DELETE')

                    <button
                        class="btn btn-outline-danger" style="width:200px;margin-top: -114px;margin-left: 267px"
                        type="submit">Supprimer definitivement</button>
                </form>
                @else


                <form action="{{
route('item.destroy', $item->id) }}"
                      method="post">
                    @csrf
                    @method('DELETE')

                    <button
                        class="btn btn-outline-danger" style="width:100px;margin-top: -67px;margin-left:170px"
                        type="submit">Supprimer</button>
                </form>
            @endif
        </td>


    </tr>

@endforeach

    </tbody>

</table>
<div class="navigation">
    {{ $items->links() }}
</div>


@endsection

resources/views/Items/show.blade.php
@extends('welcome')

@section('content')



<div class="row">
    <div class="col-md-5">
        <img src="/images/{{ $item->image }}" alt="{{ $item->title }}" class="img-fluid">
    </div>
    <div class="col-md-7 my-auto">
        <h3>{{ $item->title }}</h3>
        <p>{{ $item->title }}</p>
        <span class="product-page-price">{{ ($item->price)|number_format(2) }} €</span>
        <hr>
        <p>
            {{ $item->description }}
        </p>
    </div>
</div>
<hr>
@auth()
<div style="text-align: center">
    <a href="{{ route('item.index') }}"class="btn btn-outline-primary" style="">back to list</a>

    <a href="{{ route('item.edit', $item->id) }}" class="btn btn-outline-warning" style="">edit</a>

{{--    {{ include('items/_delete_form.html.twig') }}--}}
</div>
@endauth
       <h3>Nos meilleures ventes</h3>
        <p>Découvrez les articles les plus vendus.</p>
        <div class="row">
{{--                {% for menu in menus %}--}}
                    <div class="col-md-3">
{{--                           {% include 'item/single_item.html.twig' %}#}--}}
                       </div>

        </div><!-- /.row -->




@endsection